# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hood', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.TextField(max_length=200),
        ),
    ]
