# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hood', '0004_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Bizname',
        ),
        migrations.RemoveField(
            model_name='group',
            name='profile',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
